version: '{build}.{branch}'
build: false
deploy: false
environment:
  GOPATH: 'c:\gopath'
  PATH: 'c:\msys64\mingw64\bin\;%PATH%'
clone_folder: 'c:\test'
shallow_clone: true
test_script:
  - 'gcc --version'
  - 'mkdir %GOPATH%'
  # Go 1.10
  - 'cd %GOPATH%'
  - 'set GOROOT=c:\go110'
  - 'c:\go110\bin\go.exe get -u golang.org/x/vgo'
  - 'cd c:\test'
  - '%GOPATH%\bin\vgo.exe test -ldflags="-linkmode=external" -v -race -count=10 ./...'
  # Go 1.11
  - 'cd %GOPATH%'
  - 'set GOROOT=c:\go111'
  - 'cd c:\test'
  - '%GOROOT%\bin\go.exe test -ldflags="-linkmode=external" -v -race -count=10 ./...'
